<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="17273" started-at="2021-11-28T11:47:47Z" finished-at="2021-11-28T11:48:05Z">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="17273" started-at="2021-11-28T11:47:47Z" finished-at="2021-11-28T11:48:05Z">
      <class name="com.nopcommerce.demo.testsuite.LoginPageTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nopcommerce.demo.testsuite.LoginPageTest@3bfdc050]" name="setUp" is-config="true" duration-ms="6605" started-at="2021-11-28T11:47:47Z" finished-at="2021-11-28T11:47:54Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="verifyErrorMessageWithInvalidCredentials()[pri:0, instance:com.nopcommerce.demo.testsuite.LoginPageTest@3bfdc050]" name="verifyErrorMessageWithInvalidCredentials" duration-ms="2554" started-at="2021-11-28T11:47:54Z" finished-at="2021-11-28T11:47:56Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[login not display expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.No customer account found]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: login not display expected [Login was unsuccessful. Please correct the errors and try again.
No customer account found] but found [Login was unsuccessful. Please correct the errors and try again.No customer account found]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at com.nopcommerce.demo.testsuite.LoginPageTest.verifyErrorMessageWithInvalidCredentials(LoginPageTest.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:193)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyErrorMessageWithInvalidCredentials -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.nopcommerce.demo.testsuite.LoginPageTest@3bfdc050]" name="tearDown" is-config="true" duration-ms="774" started-at="2021-11-28T11:47:56Z" finished-at="2021-11-28T11:47:57Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.nopcommerce.demo.testsuite.LoginPageTest@3bfdc050]" name="setUp" is-config="true" duration-ms="5300" started-at="2021-11-28T11:47:57Z" finished-at="2021-11-28T11:48:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="verifyUserShouldNavigateToLoginPageSuccessFully()[pri:0, instance:com.nopcommerce.demo.testsuite.LoginPageTest@3bfdc050]" name="verifyUserShouldNavigateToLoginPageSuccessFully" duration-ms="1175" started-at="2021-11-28T11:48:03Z" finished-at="2021-11-28T11:48:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserShouldNavigateToLoginPageSuccessFully -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.nopcommerce.demo.testsuite.LoginPageTest@3bfdc050]" name="tearDown" is-config="true" duration-ms="817" started-at="2021-11-28T11:48:04Z" finished-at="2021-11-28T11:48:05Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.nopcommerce.demo.testsuite.LoginPageTest -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
